# Generated by Django 3.2.5 on 2021-09-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clginfoblog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=255)),
                ('course_id', models.IntegerField()),
                ('course', models.TextField(max_length=255)),
                ('region', models.TextField(max_length=255)),
                ('fees', models.IntegerField()),
                ('clg_type', models.TextField(max_length=255)),
            ],
        ),
    ]
