# Generated by Django 3.2.5 on 2021-10-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clginfoblog', '0003_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.TextField(default='all', max_length=255)),
                ('region', models.TextField(default='all', max_length=255)),
                ('fees', models.IntegerField()),
                ('clg_type', models.TextField(max_length=255)),
            ],
        ),
    ]
