# Generated by Django 3.2.5 on 2021-10-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clginfoblog', '0004_filters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filters',
            new_name='Filter',
        ),
    ]
