# Generated by Django 3.2.5 on 2021-10-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clginfoblog', '0006_auto_20211012_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('query', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
