# Generated by Django 3.2.5 on 2021-10-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clginfoblog', '0007_auto_20211020_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.EmailField(max_length=254),
        ),
    ]
