# Generated by Django 3.2.5 on 2021-10-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clginfoblog', '0008_alter_contact_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='clg_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
