# Generated by Django 3.2.5 on 2021-10-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clginfoblog', '0009_auto_20211023_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='clg_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='region',
            field=models.TextField(max_length=6),
        ),
    ]
